name: flutter_firebase
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5


  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.15.6
  ollama: ^1.0.2
  flutter_gemini: ^2.0.3
  google_maps_flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true